<?php
/**
 * Created by 260101081@qq.com
 * DateTime 2019-12-31 19:40
 */
namespace api\modules\v1\controllers;

use api\controllers\BaseController;
use common\models\ServeScope;
use yii\filters\auth\HttpBearerAuth;


class ServeScopeController extends BaseController
{

    public function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub

        $behaviors['authenticator'] = [
            'class' => HttpBearerAuth::className(),
            'optional' => [
                'index',
            ], //不用授权方法
        ];

        return $behaviors;
    }

    /**
     * 获取服务范围列表
     * @return array
     */
    public function actionIndex()
    {
        $model = ServeScope::find()
            ->asArray()
            ->all();
        return response($model);
    }

}
