<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/10/8
 * Time: 2:20
 */

namespace api\controllers;

use Yii;
use \yii\rest\Controller;
use \yii\filters\auth\HttpBearerAuth;

class BaseController extends Controller
{
    /*public function actions() {
        $actions = parent::actions();
        unset($actions['index'],$actions['delete'],$actions['update'], $actions['create'], $actions['view'], $actions['options']);
        return $actions;
    }*/

    public $_user;
    public $_userId;

    public function beforeAction($action)
    {
        if (parent::beforeAction($action))
        {
            $accessToken = substr(Yii::$app->request->headers['authorization'], 7);
            if ($accessToken)
            {
                $userId = Yii::$app->redis->get('login:'.$accessToken);
                if (!$userId)
                {
                    return response([], '30100');
                }
                $this->_userId = $userId;
            }
            return true;
        }
        return false;
    }

    /**
     * 登录授权
     * @return array
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub

        $behaviors['authenticator'] = [
            'class' => HttpBearerAuth::className(),
            'optional' => ['login','logout','signup', 'send-sms'], //不用授权方法
        ];

        return $behaviors;
    }



}
